# Pipeline de CI/CD para mi aplicación en Python en Windows
# Este pipeline realiza la construcción, pruebas, análisis estático,
# Dockerización, análisis de seguridad, despliegue en Kubernetes y más.

trigger:
- main  # Paso 1: rama que desees que active el pipeline

pr:
- '*'  # Paso 2: Configuración de PR (pull request)

pool:
  vmImage: 'windows-latest' 

stages:
- stage: Build  # Paso 3: Construcción de la aplicación
  jobs:
  - job: BuildJob
    steps:
    - powershell: |
        pip install -r requirements.txt
        python setup.py build
      displayName: 'Build'

- stage: Test  # Paso 4: Ejecución de pruebas
  jobs:
  - job: UnitTestJob
    steps:
    - powershell: |
        python -m unittest discover tests
      displayName: 'Run Unit Tests'

  - job: IntegrationTestJob
    steps:
    - powershell: |
        python -m unittest discover integration_tests/
      displayName: 'Run Integration Tests'

- stage: Analyze  # Paso 5: Análisis estático y cobertura de código
  jobs:
  - job: StaticCodeAnalysisJob
    steps:
    - powershell: |
        pip install pylint
        pylint my_module.py
      displayName: 'Static Code Analysis'

  - job: CodeCoverageJob
    steps:
    - powershell: |
        pip install coverage
        coverage run -m unittest discover tests/
        coverage xml -o coverage.xml
      displayName: 'Code Coverage'
    publish: 
      - codeCoverageJob
      - coverage.xml

- stage: Dockerize  # Paso 6: Dockerización de la aplicación
  jobs:
  - job: DockerizeJob
    steps:
    - powershell: |
        docker build -t devops-docker:1.0 .
        docker tag devops-docker:1.0 $(DOCKER_REGISTRY)/devops-docker:1.0
        docker push $(DOCKER_REGISTRY)/devops-docker:1.0
      displayName: 'Dockerize'

- stage: SecurityScan	# Paso 7: Análisis de seguridad de la imagen Docker
  jobs:
  - job: SecurityScanJob
    steps:
    - powershell: |
        # Ejecutar el análisis de seguridad con Trivy en la imagen Docker
        trivy image -f json devops-docker:1.0
      displayName: 'Security Scan'


- stage: DeployDev  # Paso 8a: Despliegue en entorno de desarrollo
  jobs:
  - job: DeployDevJob
    steps:
    - script:
        - kubectl apply -f deployment-dev.yaml
        - kubectl apply -f service-dev.yaml
        - kubectl apply -f configmaps-dev.yaml
        - kubectl apply -f secrets-dev.yaml
        - kubectl apply -f ingress-dev.yaml
      displayName: 'Deploy to Development'

- stage: DeployProd  # Paso 8b: Despliegue en entorno de producción
  jobs:
  - job: DeployProdJob
    steps:
    - script:
        - kubectl apply -f deployment-prod.yaml
        - kubectl apply -f service-prod.yaml
        - kubectl apply -f configmaps-prod.yaml
        - kubectl apply -f secrets-prod.yaml
        - kubectl apply -f ingress-prod.yaml
      displayName: 'Deploy to Production'

- stage: PerformanceTest  # Paso 9: Pruebas de rendimiento
  jobs:
  - job: PerformanceTestJob
    steps:
    - script:
        # Agrega tus pruebas de rendimiento aquí
        # Ejemplo: locust -f locustfile.py --headless --users 100 --spawn-rate 10
      displayName: 'Performance Test'

- stage: Monitor  # Paso 10: Monitoreo continuo con Grafana
  jobs:
  - job: MonitorJob
    steps:
    - script:
        # Configura y ejecuta tu monitoreo continuo aquí
        # Puedes instalar y configurar Grafana, Prometheus u otras herramientas
      displayName: 'Continuous Monitoring'

- stage: AcceptanceTest  # Paso 11: Pruebas de aceptación automatizadas
  jobs:
  - job: AcceptanceTestJob
    steps:
    - script:
        # Agrega tus pruebas de aceptación automatizadas aquí
      displayName: 'Automated Acceptance Tests'

- stage: Notify  # Paso 12: Notificación
  jobs:
  - job: NotifyJob
    steps:
    - script: |
        curl -X POST -H 'Content-type: application/json' --data "{\"text\":\"Pipeline de CI/CD para mi-app en la rama $(Build.SourceBranch): $(Build.PipelineWebUrl)\"}" $(SLACK_WEBHOOK)
      displayName: 'Notify'
